version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 6666:80
    restart: unless-stopped
    networks:
      - frontend-network
      - backend-network
    volumes:
      - ./data/:/var/www/html/

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./data/:/var/www/html/
    environment:
      - PMA_ARBITRARY=1
    networks:
      - backend-network

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend-network

  phpmyadmin:
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    image: phpmyadmin
    ports:
      - 6001:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - backend-network


networks:
  frontend-network:
  backend-network: